/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import MODEL.UIDATA;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.util.Date;
import javax.swing.JOptionPane;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;


/**
 *
 * @author bharv
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    UIDATA user;
    private Date Deg1start;
    private Date Deg1end;
    private Date Deg2start;
    private Date Deg2end;
    private Image Photo;
    public CreateJPanel(UIDATA user) {
        this.user = user;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FNT = new javax.swing.JTextField();
        MT = new javax.swing.JTextField();
        AFT = new javax.swing.JTextField();
        CAT = new javax.swing.JTextField();
        LNT = new javax.swing.JTextField();
        D1T = new javax.swing.JTextField();
        DT = new javax.swing.JTextField();
        D1ST = new javax.swing.JTextField();
        DOT = new javax.swing.JTextField();
        AT = new javax.swing.JTextField();
        D1ET = new javax.swing.JTextField();
        D2T = new javax.swing.JTextField();
        TELT = new javax.swing.JTextField();
        D2ST = new javax.swing.JTextField();
        ET = new javax.swing.JTextField();
        D2ET = new javax.swing.JTextField();
        ADD1T = new javax.swing.JTextField();
        ADD2T = new javax.swing.JTextField();
        EUD = new javax.swing.JLabel();
        CT = new javax.swing.JTextField();
        FN = new javax.swing.JLabel();
        COT = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        LN = new javax.swing.JLabel();
        AF = new javax.swing.JLabel();
        DATE = new javax.swing.JLabel();
        CA = new javax.swing.JLabel();
        DOB = new javax.swing.JLabel();
        MAJ = new javax.swing.JLabel();
        AGE = new javax.swing.JLabel();
        D1 = new javax.swing.JLabel();
        TELN = new javax.swing.JLabel();
        EM = new javax.swing.JLabel();
        D1E = new javax.swing.JLabel();
        D1S = new javax.swing.JLabel();
        AD1 = new javax.swing.JLabel();
        D2 = new javax.swing.JLabel();
        AD2 = new javax.swing.JLabel();
        D2S = new javax.swing.JLabel();
        CITY = new javax.swing.JLabel();
        D2E = new javax.swing.JLabel();
        CO = new javax.swing.JLabel();
        PH = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();

        FNT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FNTActionPerformed(evt);
            }
        });

        MT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MTActionPerformed(evt);
            }
        });

        AFT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AFTActionPerformed(evt);
            }
        });

        CAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CATActionPerformed(evt);
            }
        });

        D1T.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D1TActionPerformed(evt);
            }
        });

        DT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DTActionPerformed(evt);
            }
        });

        D1ST.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D1STActionPerformed(evt);
            }
        });

        DOT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DOTActionPerformed(evt);
            }
        });

        D1ET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D1ETActionPerformed(evt);
            }
        });

        D2T.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D2TActionPerformed(evt);
            }
        });

        TELT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TELTActionPerformed(evt);
            }
        });

        D2ST.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D2STActionPerformed(evt);
            }
        });

        D2ET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D2ETActionPerformed(evt);
            }
        });

        ADD1T.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD1TActionPerformed(evt);
            }
        });

        EUD.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        EUD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EUD.setText("Enter User Details");

        FN.setText("First Name:");

        jButton1.setText("Upload");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        LN.setText("Last Name:");

        AF.setText("Affiliation:");

        DATE.setText("Date:");

        CA.setText("Career:");

        DOB.setText("DOB:");

        MAJ.setText("Major:");

        AGE.setText("Age:");

        D1.setText("Degree1:");

        TELN.setText("Tel No.:");

        EM.setText("Email:");

        D1E.setText("Deg1 End:");

        D1S.setText("Deg1 Start:");

        AD1.setText("Add Line1:");

        D2.setText("Degree 2:");

        AD2.setText("Add Line2:");

        D2S.setText("Deg2 Start:");

        CITY.setText("City:");

        D2E.setText("Deg2 End:");

        CO.setText("Country:");

        PH.setText("Photo:");

        jButton2.setText("SAVE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jDesktopPane2.setMaximumSize(new java.awt.Dimension(208, 212));
        jDesktopPane2.setMinimumSize(new java.awt.Dimension(208, 212));

        jLabel2.setText("jLabel2");

        jDesktopPane2.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(117, 117, 117))
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(154, 154, 154))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EUD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(FN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FNT, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AD1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ADD1T))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LN)
                            .addComponent(DATE)
                            .addComponent(DOB)
                            .addComponent(AGE)
                            .addComponent(TELN)
                            .addComponent(EM))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TELT, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(AT)
                            .addComponent(DOT)
                            .addComponent(DT)
                            .addComponent(ET, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LNT, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AD2)
                            .addComponent(CITY)
                            .addComponent(CO))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(COT)
                            .addComponent(CT)
                            .addComponent(ADD2T))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(D2E)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(D2ET, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(D2S)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(D2ST, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(D2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(D2T, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(D1E)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(D1ET))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(AF)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(AFT, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(D1)
                                    .addGap(18, 18, 18)
                                    .addComponent(D1T))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(CA)
                                        .addComponent(D1S)
                                        .addComponent(MAJ))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(D1ST)
                                        .addComponent(CAT)
                                        .addComponent(MT))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(PH)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDesktopPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(129, 129, 129))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jButton2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(EUD, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(FNT)
                        .addComponent(AFT))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FN, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                            .addComponent(AF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LNT)
                        .addComponent(MT))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LN, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                            .addComponent(MAJ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(DT)
                        .addComponent(CAT))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DATE, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                            .addComponent(CA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(DOT)
                        .addComponent(D1T))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DOB, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                            .addComponent(D1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(AT)
                        .addComponent(D1ST))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AGE, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                            .addComponent(D1S, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TELT)
                        .addComponent(D1ET))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TELN, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                            .addComponent(D1E, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ET)
                        .addComponent(D2T))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EM, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                            .addComponent(D2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(D2ST, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(AD1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ADD1T))
                            .addComponent(D2S, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ADD2T)
                        .addComponent(D2ET))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AD2, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                            .addComponent(D2E, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(CT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CITY, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(CO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(COT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(PH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(8, 8, 8)
                                .addComponent(jButton2)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDesktopPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void MTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MTActionPerformed

    private void AFTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AFTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AFTActionPerformed

    private void CATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CATActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CATActionPerformed

    private void D1TActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D1TActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D1TActionPerformed

    private void DTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DTActionPerformed

    private void D1STActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D1STActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D1STActionPerformed

    private void D1ETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D1ETActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D1ETActionPerformed

    private void D2TActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D2TActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D2TActionPerformed

    private void D2STActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D2STActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D2STActionPerformed

    private void D2ETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D2ETActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D2ETActionPerformed

    private void ADD1TActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD1TActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ADD1TActionPerformed

    private void FNTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FNTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FNTActionPerformed

    private void DOTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DOTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DOTActionPerformed

    private void TELTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TELTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TELTActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        user.setFirstName(FNT.getText());
        user.setLastName(LNT.getText());
        user.setDate(DT.getText());
        user.setDOB(DOB.getText());
        user.setAge(AT.getText());
        user.setTelNo(TELT.getText());
        user.setEmail(ET.getText());
        user.setAdd1(ADD1T.getText());
        user.setAdd2 (ADD2T.getText());
        user.setCity(CT.getText());
        user.setCountry(COT.getText());
        user.setAffiliation(AFT.getText());
        user.setMajor(MT.getText());
        user.setCareer(CAT.getText());
        user.setDegree1(D1T.getText());
        user.setDeg1start(D1ST.getText());
        user.setDeg1end(D1ET.getText());
        user.setDegree2(D2T.getText());
        user.setDeg2start(D2ST.getText());
        user.setDeg2end(D2ET.getText());
        user.setPhoto(Photo);
        
        JOptionPane.showMessageDialog(this,"Information is Saved!");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser=new JFileChooser();
        chooser.showOpenDialog(null);
        File f=chooser.getSelectedFile();
        try {
            Photo = ImageIO.read(f);
        } catch (IOException ex) {
            Logger.getLogger(CreateJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        jLabel2.setIcon(new ImageIcon(Photo));
        filename = f.getAbsolutePath();
        PH.setText(filename);
        
        
        //try(
            //File image = new File(filename);    
            //FileInputStream fis = new FileInputStream(image); 
            //ByteArrayOutputStream bos = new ByteArrayOutputStream();
            //byte[] buf = new byte[1024];
            //    for(int readNum; (readNum=fis.read(buf))!=-1;){
              //      bos.write(buf, 0 ,read);
                //}
                  //  photo=bos.toByteArray();
            //)catch(Exception e){
                //JOptionPane.showMessageDialog(null, e);
                  //  }       
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AD1;
    private javax.swing.JLabel AD2;
    private javax.swing.JTextField ADD1T;
    private javax.swing.JTextField ADD2T;
    private javax.swing.JLabel AF;
    private javax.swing.JTextField AFT;
    private javax.swing.JLabel AGE;
    private javax.swing.JTextField AT;
    private javax.swing.JLabel CA;
    private javax.swing.JTextField CAT;
    private javax.swing.JLabel CITY;
    private javax.swing.JLabel CO;
    private javax.swing.JTextField COT;
    private javax.swing.JTextField CT;
    private javax.swing.JLabel D1;
    private javax.swing.JLabel D1E;
    private javax.swing.JTextField D1ET;
    private javax.swing.JLabel D1S;
    private javax.swing.JTextField D1ST;
    private javax.swing.JTextField D1T;
    private javax.swing.JLabel D2;
    private javax.swing.JLabel D2E;
    private javax.swing.JTextField D2ET;
    private javax.swing.JLabel D2S;
    private javax.swing.JTextField D2ST;
    private javax.swing.JTextField D2T;
    private javax.swing.JLabel DATE;
    private javax.swing.JLabel DOB;
    private javax.swing.JTextField DOT;
    private javax.swing.JTextField DT;
    private javax.swing.JLabel EM;
    private javax.swing.JTextField ET;
    private javax.swing.JLabel EUD;
    private javax.swing.JLabel FN;
    private javax.swing.JTextField FNT;
    private javax.swing.JLabel LN;
    private javax.swing.JTextField LNT;
    private javax.swing.JLabel MAJ;
    private javax.swing.JTextField MT;
    private javax.swing.JLabel PH;
    private javax.swing.JLabel TELN;
    private javax.swing.JTextField TELT;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
byte[] photo=null;
String filename=null;
}
