/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import MODEL.UIDATA;

/**
 *
 * @author bharv
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    UIDATA user;
    public ViewJPanel(UIDATA user) {
        this.user = user;
        initComponents();
        this.displayUIDATA();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EUD = new javax.swing.JLabel();
        FN = new javax.swing.JLabel();
        LN = new javax.swing.JLabel();
        DATE = new javax.swing.JLabel();
        DOB = new javax.swing.JLabel();
        AGE = new javax.swing.JLabel();
        TELNO = new javax.swing.JLabel();
        EMAIL = new javax.swing.JLabel();
        ADDLINE1 = new javax.swing.JLabel();
        ADDLINE2 = new javax.swing.JLabel();
        CITY = new javax.swing.JLabel();
        COUNTRY = new javax.swing.JLabel();
        FNT = new javax.swing.JTextField();
        AFT = new javax.swing.JTextField();
        LNT = new javax.swing.JTextField();
        DT = new javax.swing.JTextField();
        DOBT = new javax.swing.JTextField();
        AT = new javax.swing.JTextField();
        TELT = new javax.swing.JTextField();
        ET = new javax.swing.JTextField();
        ADT = new javax.swing.JTextField();
        ADT2 = new javax.swing.JTextField();
        CT = new javax.swing.JTextField();
        COT = new javax.swing.JTextField();
        AF = new javax.swing.JLabel();
        CAREER = new javax.swing.JLabel();
        MAJOR = new javax.swing.JLabel();
        D1 = new javax.swing.JLabel();
        D1E = new javax.swing.JLabel();
        D1S = new javax.swing.JLabel();
        D2 = new javax.swing.JLabel();
        D2S = new javax.swing.JLabel();
        D2E = new javax.swing.JLabel();
        PHOTO = new javax.swing.JLabel();
        MT = new javax.swing.JTextField();
        CAT = new javax.swing.JTextField();
        D1T = new javax.swing.JTextField();
        D1ST = new javax.swing.JTextField();
        D1ET = new javax.swing.JTextField();
        D2T = new javax.swing.JTextField();
        D2ST = new javax.swing.JTextField();
        D2ET = new javax.swing.JTextField();
        UPLOAD = new javax.swing.JButton();

        EUD.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        EUD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EUD.setText("View User Details");

        FN.setText("First Name:");

        LN.setText("Last Name:");

        DATE.setText("Date:");

        DOB.setText("DOB:");

        AGE.setText("Age:");

        TELNO.setText("Tel No.:");

        EMAIL.setText("Email:");

        ADDLINE1.setText("Add Line1:");

        ADDLINE2.setText("Add Line2:");

        CITY.setText("City:");

        COUNTRY.setText("Country:");

        AFT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AFTActionPerformed(evt);
            }
        });

        DT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DTActionPerformed(evt);
            }
        });

        ADT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADTActionPerformed(evt);
            }
        });

        ADT2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADT2ActionPerformed(evt);
            }
        });

        AF.setText("Affiliation:");

        CAREER.setText("Career:");

        MAJOR.setText("Major:");

        D1.setText("Degree1:");

        D1E.setText("Deg1 End:");

        D1S.setText("Deg1 Start:");

        D2.setText("Degree 2:");

        D2S.setText("Deg2 Start:");

        D2E.setText("Deg2 End:");

        PHOTO.setText("Photo:");

        MT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MTActionPerformed(evt);
            }
        });

        CAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CATActionPerformed(evt);
            }
        });

        D1T.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D1TActionPerformed(evt);
            }
        });

        D1ST.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D1STActionPerformed(evt);
            }
        });

        D1ET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D1ETActionPerformed(evt);
            }
        });

        D2T.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D2TActionPerformed(evt);
            }
        });

        D2ST.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D2STActionPerformed(evt);
            }
        });

        D2ET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D2ETActionPerformed(evt);
            }
        });

        UPLOAD.setText("Upload");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EUD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(FN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FNT))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ADDLINE2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ADT2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ADDLINE1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ADT))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(EMAIL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ET))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TELNO)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TELT))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AGE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AT))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(DOB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DOBT))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(DATE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DT))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LNT))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CITY)
                        .addGap(25, 25, 25)
                        .addComponent(CT))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(COUNTRY)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(COT, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(D2E)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(D2ET))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(D2S)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(D2ST))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(D2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(D2T))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(D1E)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(D1ET))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(D1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(D1T))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CAREER)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CAT))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AFT))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(D1S)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(D1ST))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(MAJOR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MT, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(PHOTO)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UPLOAD)))
                .addGap(92, 92, 92))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(EUD, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FN)
                    .addComponent(FNT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AFT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LN)
                    .addComponent(LNT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MAJOR)
                    .addComponent(MT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DATE)
                    .addComponent(DT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CAREER)
                    .addComponent(CAT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DOB)
                    .addComponent(DOBT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(D1)
                    .addComponent(D1T, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AGE)
                    .addComponent(AT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(D1S)
                    .addComponent(D1ST, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TELNO)
                    .addComponent(TELT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(D1E)
                    .addComponent(D1ET, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EMAIL)
                    .addComponent(ET, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(D2)
                    .addComponent(D2T, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ADDLINE1)
                    .addComponent(ADT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(D2S)
                    .addComponent(D2ST, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ADDLINE2)
                    .addComponent(ADT2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(D2E)
                    .addComponent(D2ET, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CITY)
                            .addComponent(CT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(COUNTRY)
                            .addComponent(COT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PHOTO)
                            .addComponent(UPLOAD))))
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void DTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DTActionPerformed

    private void AFTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AFTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AFTActionPerformed

    private void MTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MTActionPerformed

    private void CATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CATActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CATActionPerformed

    private void D1TActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D1TActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D1TActionPerformed

    private void D1STActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D1STActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D1STActionPerformed

    private void D1ETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D1ETActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D1ETActionPerformed

    private void D2TActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D2TActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D2TActionPerformed

    private void D2STActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D2STActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D2STActionPerformed

    private void D2ETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D2ETActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D2ETActionPerformed

    private void ADTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ADTActionPerformed

    private void ADT2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADT2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ADT2ActionPerformed
    
    private void displayUIDATA(){
        FNT.setText(user.getFirstName());
        LNT.setText(user.getLastName());
        DT.setText(user.getDate());
        DOBT.setText(user.getDOB());
        AT.setText(user.getAge());
        TELT.setText(user.getTelNo());
        ET.setText(user.getEmail());
        ADT.setText(user.getAdd1());
        ADT2.setText(user.getAdd2());
        CT.setText(user.getCity());
        COT.setText(user.getCountry());
        AFT.setText(user.getAffiliation());
        MT.setText(user.getMajor());
        CAT.setText(user.getCareer());
        D1T.setText(user.getDegree1());
        D1ST.setText(user.getDeg1start());
        D1ET.setText(user.getDeg1end());
        D2T.setText(user.getDegree2());
        D2ST.setText(user.getDeg2start());
        D2ET.setText(user.getDeg2end());
        //PHOTO.setText(user.getPhoto().toString());
    
    
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ADDLINE1;
    private javax.swing.JLabel ADDLINE2;
    private javax.swing.JTextField ADT;
    private javax.swing.JTextField ADT2;
    private javax.swing.JLabel AF;
    private javax.swing.JTextField AFT;
    private javax.swing.JLabel AGE;
    private javax.swing.JTextField AT;
    private javax.swing.JLabel CAREER;
    private javax.swing.JTextField CAT;
    private javax.swing.JLabel CITY;
    private javax.swing.JTextField COT;
    private javax.swing.JLabel COUNTRY;
    private javax.swing.JTextField CT;
    private javax.swing.JLabel D1;
    private javax.swing.JLabel D1E;
    private javax.swing.JTextField D1ET;
    private javax.swing.JLabel D1S;
    private javax.swing.JTextField D1ST;
    private javax.swing.JTextField D1T;
    private javax.swing.JLabel D2;
    private javax.swing.JLabel D2E;
    private javax.swing.JTextField D2ET;
    private javax.swing.JLabel D2S;
    private javax.swing.JTextField D2ST;
    private javax.swing.JTextField D2T;
    private javax.swing.JLabel DATE;
    private javax.swing.JLabel DOB;
    private javax.swing.JTextField DOBT;
    private javax.swing.JTextField DT;
    private javax.swing.JLabel EMAIL;
    private javax.swing.JTextField ET;
    private javax.swing.JLabel EUD;
    private javax.swing.JLabel FN;
    private javax.swing.JTextField FNT;
    private javax.swing.JLabel LN;
    private javax.swing.JTextField LNT;
    private javax.swing.JLabel MAJOR;
    private javax.swing.JTextField MT;
    private javax.swing.JLabel PHOTO;
    private javax.swing.JLabel TELNO;
    private javax.swing.JTextField TELT;
    private javax.swing.JButton UPLOAD;
    // End of variables declaration//GEN-END:variables
}
